### DISCUSSION TITLE
Missing entities for power limits for individual automations

### DISCUSSION THREAD

**Discussion by Bertk** [matfroh/sax_battery_ha#7] [General]
Thank you for this integration which simplifies the SAX battery handling and will be a big improvement for all HA sax power users.

**Currently I have only one battery and set the limits in dynamic way.**

<img width="248" alt="Image" src="https://github.com/user-attachments/assets/6109d8ae-8029-47ea-8ee6-397d4007197e" />

**limit_power:** 

I use `input_select` to set the limit via automation.

Criterias:
 
- actual PV production
- actual power consumption
- actual price for electricity tariff

```
sax_a_leistungsgrenzwert_entladen:
  name: Leistungsgrenzwert Entladen
  initial: "0"
  options:
    - "4600"
    - "2500"
    - "1000"
    - "500"
    - "0"
  icon: mdi:battery-arrow-up
sax_a_leistungsgrenzwert_laden:
  name: Leistungsgrenzwert Laden
  initial: "3500"
  options:
    - "3500"
    - "0"
  icon: mdi:battery-arrow-down-outline
```

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/991c8d75-ee24-488c-8e7e-85b16e7ba9e0" />

- sensor.battery_combined_power entity should only be created for 2 of 3 batteries
- please use a different UI element for number of batteries configuration

<img width="296" alt="Image" src="https://github.com/user-attachments/assets/87bae80c-deb9-49e7-888f-59240f75b2d1" />

- no description for power limit and pilot_from_ha

<img width="293" alt="Image" src="https://github.com/user-attachments/assets/3aaea8eb-0d3b-4531-a1dc-1dabb1be529e" />

- please use a prefix for the entity names which will sorting and searching much easier

Finally I switched back to my modbus.yaml configuration because setting power limits is not possible.
